TRACK_METADATA = {
    "bahrain": {
        "circuit_id": "circuit_id_bahrain",
        "display_name": "Bahrain",
        "url_name": "bahrain",
        "race_ids": {
            2010: 860,
            2012: 13,
            2013: 882,
            2014: 900,
            2015: 920,
            2016: 939,
            2017: 961,
            2018: 980,
            2019: 1001,
            2020: 1059,
            2021: 1064,
            2022: 1124,
            2023: 1141,
            2024: 1229,
            2025: 1257,
        },
        "flag": "Flag_of_Bahrain.png",
        "detailed_flag": "Bahrain.png",
        "annotated_layout": "bahrain.avif",
        "layout": "bahrain.png",
        "detailed_track_image": "Detailed_Bahrain.jpg",
        "detailed_track_attribution": "Derek Morrison from Kuwait, Kuwait, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "Bahrain_Grand_Prix"
    },
    "jeddah": {
        "circuit_id": "circuit_id_jeddah",
        "display_name": "Saudi Arabia",
        "url_name": "saudi-arabia",
        "race_ids": {
            2021: 1106,
            2022: 1125,
            2023: 1142,
            2024: 1230,
            2025: 1258,
        },
        "flag": "Flag_of_Saudi_Arabia.png",
        "detailed_flag": "Saudi_Arabia.png",
        "annotated_layout": "jeddah.avif",
        "layout": "jeddah.png",
        "detailed_track_image": "Detailed_Saudi_Arabia.jpg",
        "detailed_track_attribution": "Joseph Azrak, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Saudi_Arabian_Grand_Prix"
    },
    "albert-park": {
        "circuit_id": "circuit_id_albert_park",
        "display_name": "Australia",
        "url_name": "australia",
        "race_ids": {
            2010: 861,
            2011: 28,
            2012: 10,
            2013: 879,
            2014: 898,
            2015: 917,
            2016: 938,
            2017: 959,
            2018: 979,
            2019: 1000,
            2022: 1208,
            2023: 1143,
            2024: 1231,
            2025: 1254,
        },
        "flag": "Flag_of_Australia.png",
        "detailed_flag": "Australia.png",
        "annotated_layout": "albert-park.avif",
        "layout": "albert_park.png",
        "detailed_track_image": "Detailed_Australia.jpg",
        "detailed_track_attribution": "Chris Phutully, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "Australian_Grand_Prix"
    },
    "suzuka": {
        "circuit_id": "circuit_id_suzuka",
        "display_name": "Suzuka",
        "url_name": "japan",
        "race_ids": {
            2010: 875,
            2011: 42,
            2012: 22,
            2013: 893,
            2014: 912,
            2015: 931,
            2016: 953,
            2017: 974,
            2018: 995,
            2019: 1016,
            2022: 1134,
            2023: 1220,
            2024: 1232,
            2025: 1256,
        },
        "flag": "Flag_of_Japan.png",
        "detailed_flag": "Japan.png",
        "annotated_layout": "suzuka.avif",
        "layout": "suzuka.png",
        "detailed_track_image": "Detailed_Japan.jpg",
        "detailed_track_attribution": "Tokumeigakarinoaoshima, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Japanese_Grand_Prix"
    },
    "shanghai": {
        "circuit_id": "circuit_id_shanghai",
        "display_name": "Shanghai",
        "url_name": "china",
        "race_ids": {
            2010: 863,
            2011: 30,
            2012: 12,
            2013: 881,
            2014: 901,
            2015: 919,
            2016: 940,
            2017: 960,
            2018: 981,
            2019: 1002,
            2024: 1233,
            2025: 1255,
        },
        "flag": "Flag_of_China.png",
        "detailed_flag": "China.png",
        "annotated_layout": "shanghai.avif",
        "layout": "shanghai.png",
        "detailed_track_image": "Detailed_China.jpg",
        "detailed_track_attribution": "sjiong, CC BY-SA 2.0 <https://creativecommons.org/licenses/by-sa/2.0>, via Wikimedia Commons",
        "wiki": "Chinese_Grand_Prix"
    },
    "miami": {
        "circuit_id": "circuit_id_miami",
        "display_name": "Miami",
        "url_name": "miami",
        "race_ids": {
            2022: 1110,
            2023: 1208,
            2024: 1234,
            2025: 1259,
        },
        "flag": "Flag_of_USA.png",
        "detailed_flag": "USA.png",
        "annotated_layout": "miami.avif",
        "layout": "miami.png",
        "detailed_track_image": "Detailed_Miami.jpg",
        "detailed_track_attribution": "Bassfish22, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Miami_Grand_Prix"
    },
    "imola": {
        "circuit_id": "circuit_id_imola",
        "display_name": "Imola",
        "url_name": "italy",
        "race_ids": {
            2020: 1057,
            2021: 1065,
            2022: 1109,
            2024: 1235,
            2025: 1260,
        },
        "flag": "Flag_of_Italy.png",
        "detailed_flag": "Italy.png",
        "annotated_layout": "imola.avif",
        "layout": "imola.png",
        "detailed_track_image": "Detailed_Imola.jpg",
        "detailed_track_attribution": "",
        "wiki": "Emilia_Romagna_Grand_Prix"
    },
    "monaco": {
        "circuit_id": "circuit_id_monaco",
        "display_name": "Monaco",
        "url_name": "monaco",
        "race_ids": {
            2010: 865,
            2011: 33,
            2012: 15,
            2013: 884,
            2014: 903,
            2015: 922,
            2016: 943,
            2017: 964,
            2018: 984,
            2019: 1005,
            2021: 1067,
            2022: 1112,
            2023: 1210,
            2024: 1236,
            2025: 1261,
        },
        "flag": "Flag_of_Monaco.png",
        "detailed_flag": "Monaco.png",
        "annotated_layout": "monaco.avif",
        "layout": "monaco.png",
        "detailed_track_image": "Detailed_Monaco.jpg",
        "detailed_track_attribution": "Alexander Migl, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Monaco_Grand_Prix"
    },
    "villeneuve": {
        "circuit_id": "circuit_id_villeneuve",
        "display_name": "Canada",
        "url_name": "canada",
        "race_ids": {
            2010: 867,
            2011: 34,
            2012: 16,
            2013: 885,
            2014: 904,
            2015: 923,
            2016: 944,
            2017: 965,
            2018: 985,
            2019: 1006,
            2022: 1113,
            2023: 1212,
            2024: 1237,
            2025: 1263,
        },
        "flag": "Flag_of_Canada.png",
        "detailed_flag": "Canada.png",
        "annotated_layout": "villeneuve.avif",
        "layout": "villeneuve.png",
        "detailed_track_image": "Detailed_Canada.jpg",
        "detailed_track_attribution": "kevint3141 from Kitchener, Canada, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "Canadian_Grand_Prix"
    },
    "catalunya": {
        "circuit_id": "circuit_id_catalunya",
        "display_name": "Catalunya",
        "url_name": "spain",
        "race_ids": {
            2010: 864,
            2011: 32,
            2012: 14,
            2013: 883,
            2014: 902,
            2015: 921,
            2016: 942,
            2017: 963,
            2018: 983,
            2019: 1004,
            2020: 1050,
            2021: 1086,
            2022: 1111,
            2023: 1211,
            2024: 1238,
            2025: 1262,
        },
        "flag": "Flag_of_Spain.png",
        "detailed_flag": "Spain.png",
        "annotated_layout": "catalunya.avif",
        "layout": "catalunya.png",
        "detailed_track_image": "Detailed_Spain.jpg",
        "detailed_track_attribution": "Wilnel José Verdú Guerrero, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Spanish_Grand_Prix"
    },
    "red-bull-ring": {
        "circuit_id": "circuit_id_red_bull_ring",
        "display_name": "Austria",
        "url_name": "austria",
        "race_ids": {
            2014: 905,
            2015: 924,
            2016: 945,
            2017: 967,
            2018: 987,
            2019: 1008,
            2020: 1045,
            2021: 1071,
            2022: 1115,
            2023: 1213,
            2024: 1239,
            2025: 1264,
        },
        "flag": "Flag_of_Austria.png",
        "detailed_flag": "Austria.png",
        "annotated_layout": "red-bull-ring.avif",
        "layout": "red_bull_ring.png",
        "detailed_track_image": "Detailed_Austria.jpg",
        "detailed_track_attribution": "https://www.flickr.com/photos/pedrik, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "Austrian_Grand_Prix"
    },
    "silverstone": {
        "circuit_id": "circuit_id_silverstone",
        "display_name": "Silverstone",
        "url_name": "great-britain",
        "race_ids": {
            2010: 869,
            2011: 36,
            2012: 4,
            2013: 886,
            2014: 906,
            2015: 925,
            2016: 946,
            2017: 968,
            2018: 988,
            2019: 1009,
            2020: 1048,
            2021: 1072,
            2022: 1114,
            2023: 1214,
            2024: 1240,
            2025: 1277,
        },
        "flag": "Flag_of_UK.png",
        "detailed_flag": "United_Kingdom.png",
        "annotated_layout": "silverstone.avif",
        "layout": "silverstone.png",
        "detailed_track_image": "Detailed_United_Kingdom.jpg",
        "detailed_track_attribution": "Becketts Stand, Silverstone. by David Ashcroft, CC BY-SA 2.0 <https://creativecommons.org/licenses/by-sa/2.0>, via Wikimedia Commons",
        "wiki": "British_Grand_Prix"
    },
    "hungaroring": {
        "circuit_id": "circuit_id_hungaroring",
        "display_name": "Hungary",
        "url_name": "hungary",
        "race_ids": {
            2010: 871,
            2011: 38,
            2012: 1,
            2013: 888,
            2014: 908,
            2015: 927,
            2016: 947,
            2017: 969,
            2018: 990,
            2019: 1011,
            2020: 1047,
            2021: 1073,
            2022: 1117,
            2023: 1215,
            2024: 1241,
            2025: 1266,
        },
        "flag": "Flag_of_Hungary.png",
        "detailed_flag": "Hungary.png",
        "annotated_layout": "hungaroring.avif",
        "layout": "hungaroring.png",
        "detailed_track_image": "Detailed_Hungary.jpg",
        "detailed_track_attribution": "Derzsi Elekes Andor (talk · contribs), CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Hungarian_Grand_Prix"
    },
    "spa": {
        "circuit_id": "circuit_id_spa",
        "display_name": "Belgium",
        "url_name": "belgium",
        "race_ids": {
            2010: 872,
            2011: 39,
            2012: 19,
            2013: 889,
            2014: 909,
            2015: 928,
            2016: 949,
            2017: 970,
            2018: 991,
            2019: 1012,
            2020: 1051,
            2021: 1074,
            2022: 1118,
            2023: 1216,
            2024: 1242,
            2025: 1265,
        },
        "flag": "Flag_of_Belgium.png",
        "detailed_flag": "Belgium.png",
        "annotated_layout": "spa.avif",
        "layout": "spa.png",
        "detailed_track_image": "Detailed_Belgium.jpg",
        "detailed_track_attribution": "Cutkiller2018, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Belgian_Grand_Prix"
    },
    "zanvoort": {
        "circuit_id": "circuit_id_zandvoort",
        "display_name": "Netherlands",
        "url_name": "netherlands",
        "race_ids": {
            2021: 1075,
            2022: 1119,
            2023: 1217,
            2024: 1243,
            2025: 1267,
        },
        "flag": "Flag_of_Netherlands.png",
        "detailed_flag": "Netherlands.png",
        "annotated_layout": "zandvoort.avif",
        "layout": "zandvoort.png",
        "detailed_track_image": "Detailed_Netherlands.jpg",
        "detailed_track_attribution": "dronepicr, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "Dutch_Grand_Prix"
    },
    "monza": {
        "circuit_id": "circuit_id_monza",
        "display_name": "Monza",
        "url_name": "italy",
        "race_ids": {
            2010: 873,
            2011: 40,
            2012: 20,
            2013: 890,
            2014: 910,
            2015: 929,
            2016: 950,
            2017: 971,
            2018: 992,
            2019: 1013,
            2020: 1051,
            2021: 1076,
            2022: 1120,
            2023: 1218,
            2024: 1244,
            2025: 1268,
        },
        "flag": "Flag_of_Italy.png",
        "detailed_flag": "Italy.png",
        "annotated_layout": "monza.avif",
        "layout": "monza.png",
        "detailed_track_image": "Detailed_Italy.jpg",
        "detailed_track_attribution": "pedrik, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "Italian_Grand_Prix"
    },
    "baku": {
        "circuit_id": "circuit_id_baku",
        "display_name": "Azerbaijan",
        "url_name": "azerbaijan",
        "race_ids": {
            2016: 958,
            2017: 966,
            2018: 982,
            2019: 1003,
            2021: 1068,
            2022: 1126,
            2023: 1207,
            2024: 1245,
            2025: 1269,
        },
        "flag": "Flag_of_Azerbaijan.png",
        "detailed_flag": "Azerbaijan.png",
        "annotated_layout": "baku.avif",
        "layout": "baku.png",
        "detailed_track_image": "Detailed_Azerbaijan.jpg",
        "detailed_track_attribution": "President.az, CC BY 4.0 <https://creativecommons.org/licenses/by/4.0>, via Wikimedia Commons",
        "wiki": "Azerbaijan_Grand_Prix"
    },
    "marina-bay": {
        "circuit_id": "circuit_id_marina_bay",
        "display_name": "Singapore",
        "url_name": "singapore",
        "race_ids": {
            2010: 874,
            2011: 41,
            2012: 21,
            2013: 891,
            2014: 911,
            2015: 930,
            2016: 951,
            2017: 972,
            2018: 993,
            2019: 1014,
            2022: 1133,
            2023: 1219,
            2024: 1246,
            2025: 9999,
        },
        "flag": "Flag_of_Singapore.png",
        "detailed_flag": "Singapore.png",
        "annotated_layout": "marina-bay.avif",
        "layout": "marina_bay.png",
        "detailed_track_image": "Detailed_Singapore.jpg",
        "detailed_track_attribution": "chensiyuan, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Singapore_Grand_Prix"
    },
    "americas": {
        "circuit_id": "circuit_id_americas",
        "display_name": "Americas",
        "url_name": "united-states",
        "race_ids": {
            2012: 26,
            2013: 896,
            2014: 914,
            2015: 933,
            2016: 954,
            2017: 975,
            2018: 996,
            2019: 1018,
            2021: 1102,
            2022: 1135,
            2023: 1222,
            2024: 1247,
            2025: 9999,
        },
        "flag": "Flag_of_USA.png",
        "detailed_flag": "USA.png",
        "annotated_layout": "americas.avif",
        "layout": "americas.png",
        "detailed_track_image": "Detailed_United_States.jpg",
        "detailed_track_attribution": "Zach Catanzareti Photo, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "United_States_Grand_Prix"
    },
    "rodriguez": {
        "circuit_id": "circuit_id_rodriguez",
        "display_name": "Mexico",
        "url_name": "mexico",
        "race_ids": {
            2015: 934,
            2016: 955,
            2017: 976,
            2018: 997,
            2019: 1017,
            2021: 1103,
            2022: 1136,
            2023: 1223,
            2024: 1248,
            2025: 9999,
        },
        "flag": "Flag_of_Mexico.png",
        "detailed_flag": "Mexico.png",
        "annotated_layout": "rodriguez.avif",
        "layout": "rodriguez.png",
        "detailed_track_image": "Detailed_Mexico.jpg",
        "detailed_track_attribution": "Tsoncch22, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Mexican_Grand_Prix"
    },
    "interlagos": {
        "circuit_id": "circuit_id_interlagos",
        "display_name": "Brazil",
        "url_name": "brazil",
        "race_ids": {
            2010: 877,
            2011: 46,
            2012: 27,
            2013: 897,
            2014: 915,
            2015: 935,
            2016: 956,
            2017: 977,
            2018: 998,
            2019: 1019,
            2021: 1104,
            2022: 1137,
            2023: 1224,
            2024: 1249,
            2025: 9999,
        },
        "flag": "Flag_of_Brazil.png",
        "detailed_flag": "Brazil.png",
        "annotated_layout": "interlagos.avif",
        "layout": "interlagos.png",
        "detailed_track_image": "Detailed_Brazil.jpg",
        "detailed_track_attribution": "Boaventuravinicius, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Brazilian_Grand_Prix"
    },
    "vegas": {
        "circuit_id": "circuit_id_vegas",
        "display_name": "Las Vegas",
        "url_name": "las-vegas",
        "race_ids": {
            2023: 1225,
            2024: 1250,
            2025: 9999,
        },
        "flag": "Flag_of_USA.png",
        "detailed_flag": "USA.png",
        "annotated_layout": "vegas.avif",
        "layout": "vegas.png",
        "detailed_track_image": "Detailed_Las_Vegas.jpg",
        "detailed_track_attribution": "5chw4r7z, CC BY-SA 2.0 <https://creativecommons.org/licenses/by-sa/2.0>, via Wikimedia Commons",
        "wiki": "Las_Vegas_Grand_Prix"
    },
    "losail": {
        "circuit_id": "circuit_id_losail",
        "display_name": "Qatar",
        "url_name": "qatar",
        "race_ids": {
            2021: 1105,
            2023: 1221,
            2024: 1251,
            2025: 9999,
        },
        "flag": "Flag_of_Qatar.png",
        "detailed_flag": "Qatar.png",
        "annotated_layout": "losail.avif",
        "layout": "losail.png",
        "detailed_track_image": "Detailed_Qatar.jpg",
        "detailed_track_attribution": "Trinidade, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
        "wiki": "Qatar_Grand_Prix"
    },
    "yas-marina": {
        "circuit_id": "circuit_id_yas_marina",
        "display_name": "Abu Dhabi",
        "url_name": "abu-dhabi",
        "race_ids": {
            2010: 878,
            2011: 45,
            2012: 25,
            2013: 895,
            2014: 916,
            2015: 936,
            2016: 957,
            2017: 978,
            2018: 999,
            2019: 1020,
            2020: 1061,
            2021: 1107,
            2022: 1138,
            2023: 1226,
            2024: 1252,
            2025: 9999,
        },
        "flag": "Flag_of_UAE.png",
        "detailed_flag": "Abu_Dhabi.png",
        "annotated_layout": "yas-marina.avif",
        "layout": "yas_marina.png",
        "detailed_track_image": "Detailed_Abu_Dhabi.jpg",
        "detailed_track_attribution": "Cesar I. Martins, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "Abu_Dhabi_Grand_Prix"
    },
    "ricard": {
        "circuit_id": "circuit_id_ricard",
        "display_name": "Paul Ricard",
        "url_name": "france",
        "race_ids": {
            2018: 986,
            2019: 1007,
            2021: 1070,
            2022: 1116,
        },
        "flag": "Flag_of_France.png",
        "detailed_flag": "France.png",
        "annotated_layout": "ricard.avif",
        "layout": "ricard.png",
        "detailed_track_image": "Detailed_Ricard.png",
        "detailed_track_attribution": "Francois Oreca, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
        "wiki": "French_Grand_Prix"
    },
    "sochi": {
        "circuit_id": "circuit_id_sochi",
        "display_name": "Sochi",
        "url_name": "russia",
        "race_ids": {
            2014: 913,
            2015: 932,
            2016: 941,
            2017: 962,
            2018: 994,
            2019: 1015,
            2020: 1054,
            2021: 1077,
        },
        "flag": "Flag_of_Russia.png",
        "detailed_flag": "Russia.png",
        "annotated_layout": "sochi.avif",
        "layout": "sochi.png",
        "detailed_track_image": "Detailed_Sochi.jpg",
        "detailed_track_attribution": "Stolbovsky, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
        "wiki": "Russian_Grand_Prix"
    },
    "portimao": {
        "circuit_id": "circuit_id_portimao",
        "display_name": "Portimão",
        "url_name": "portugal",
        "race_ids": {
            2020: 1056,
            2021: 1066,
        },
        "flag": "Flag_of_Portugal.png",
        "detailed_flag": "Portugal.png",
        "annotated_layout": "portimao.avif",
        "layout": "portimao.png",
        "detailed_track_image": "Detailed_Portimao.jpg",
        "detailed_track_attribution": "Klugschnacker, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
        "wiki": "Portuguese_Grand_Prix"
    },
    "istanbul": {
        "circuit_id": "circuit_id_istanbul",
        "display_name": "Istanbul",
        "url_name": "turkey",
        "race_ids": {
            2010: 866,
            2011: 31,
            2020: 1058,
            2021: 1078,
        },
        "flag": "Flag_of_Turkey.png",
        "detailed_flag": "Turkey.png",
        "annotated_layout": "istanbul.avif",
        "layout": "istanbul.png",
        "detailed_track_image": "Detailed_Istanbul.jpg",
        "detailed_track_attribution": "Homonihilis, CC BY 3.0 <https://creativecommons.org/licenses/by/3.0>, via Wikimedia Commons",
        "wiki": "Turkish_Grand_Prix"
    },
    "mugello": {
        "circuit_id": "circuit_id_mugello",
        "display_name": "Mugello",
        "url_name": "tuscany",
        "race_ids": {
            2020: 1053,
        },
        "flag": "Flag_of_Italy.png",
        "detailed_flag": "Italy.png",
        "annotated_layout": "mugello.avif",
        "layout": "mugello.png",
        "detailed_track_image": "Detailed_Mugello.jpg",
        "detailed_track_attribution": "Anna.Massini, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Tuscan_Grand_Prix"
    },
    "nurburgring": {
        "circuit_id": "circuit_id_nurburgring",
        "display_name": "Nürburgring",
        "url_name": "germany",
        "race_ids": {
            2011: 37,
            2013: 887,
            2020: 1055,
        },
        "flag": "Flag_of_Germany.png",
        "detailed_flag": "Germany.png",
        "annotated_layout": "nurburgring.avif",
        "layout": "nurburgring.png",
        "detailed_track_image": "Detailed_Nurburgring.jpg",
        "detailed_track_attribution": "qwesy qwesy, CC BY 3.0 <https://creativecommons.org/licenses/by/3.0>, via Wikimedia Commons",
        "wiki": "Eifel_Grand_Prix"
    },
    "hockenheimring": {
        "circuit_id": "circuit_id_hockenheimring",
        "display_name": "Hockenheim",
        "url_name": "germany",
        "race_ids": {
            2010: 870,
            2012: 18,
            2014: 907,
            2016: 948,
            2018: 989,
            2019: 1010,
        },
        "flag": "Flag_of_Germany.png",
        "detailed_flag": "Germany.png",
        "annotated_layout": "hockenheimring.avif",
        "layout": "hockenheimring.png",
        "detailed_track_image": "Detailed_Hockenheimring.jpg",
        "detailed_track_attribution": "Justin LaBerge, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": ""
    },
    "sepang": {
        "circuit_id": "circuit_id_sepang",
        "display_name": "Sepang",
        "url_name": "malaysia",
        "race_ids": {
            2010: 862,
            2011: 29,
            2012: 11,
            2013: 880,
            2014: 899,
            2015: 918,
            2016: 952,
            2017: 973,
        },
        "flag": "Flag_of_Malaysia.png",
        "detailed_flag": "Malaysia.png",
        "annotated_layout": "sepang.avif",
        "layout": "sepang.png",
        "detailed_track_image": "Detailed_Sepang.jpg",
        "detailed_track_attribution": "Postmortem at Russian Wikipedia, Public domain, via Wikimedia Commons",
        "wiki": "Malaysian_Grand_Prix"
    },
    "yeongam": {
        "circuit_id": "circuit_id_yeongam",
        "display_name": "Yeongam",
        "url_name": "south-korea",
        "race_ids": {
            2010: 876,
            2011: 43,
            2012: 23,
            2013: 892,
        },
        "flag": "Flag_of_South_Korea.png",
        "detailed_flag": "South_Korea.png",
        "annotated_layout": "yeongam.avif",
        "layout": "yeongam.png",
        "detailed_track_image": "Detailed_Yeongam.jpg",
        "detailed_track_attribution": "LG전자, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "Korean_Grand_Prix"
    },
    "buddh": {
        "circuit_id": "circuit_id_buddh",
        "display_name": "Buddh",
        "url_name": "india",
        "race_ids": {
            2011: 44,
            2012: 24,
            2013: 894,
        },
        "flag": "Flag_of_India.png",
        "detailed_flag": "India.png",
        "annotated_layout": "buddh.avif",
        "layout": "buddh.png",
        "detailed_track_image": "Detailed_Buddh.jpg",
        "detailed_track_attribution": "Alok09031995, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "wiki": "Indian_Grand_Prix"
    },
    "valencia": {
        "circuit_id": "circuit_id_valencia",
        "display_name": "Valencia",
        "url_name": "europe",
        "race_ids": {
            2010: 868,
            2011: 35,
            2012: 17,
        },
        "flag": "Flag_of_Spain.png",
        "detailed_flag": "Spain.png",
        "annotated_layout": "valencia.avif",
        "layout": "valencia.png",
        "detailed_track_image": "Detailed_Valencia.jpg",
        "detailed_track_attribution": "16:9clue, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "wiki": "European_Grand_Prix"
    },
}