TRACK_METADATA = {
    "bahrain": {
        "circuit_id": "circuit_id_bahrain",
        "display_name": "Bahrain",
        "f1_website": "2024/bahrain",
        "flag": "Flag_of_Bahrain.png",
        "detailed_flag": "Bahrain.png",
        "annotated_layout": "bahrain.avif",
        "layout": "bahrain.png",
        "detailed_track_image": "Detailed_Bahrain.jpg",
        "detailed_track_attribution": "Derek Morrison from Kuwait, Kuwait, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "round": 1,
        "wiki": "2024_Bahrain_Grand_Prix",
        "date": "2nd March",
    },
    "saudi-arabia": {
        "circuit_id": "circuit_id_jeddah",
        "display_name": "Saudi Arabia",
        "f1_website": "2024/saudi-arabia",
        "flag": "Flag_of_Saudi_Arabia.png",
        "detailed_flag": "Saudi_Arabia.png",
        "annotated_layout": "saudi-arabia.avif",
        "layout": "saudi_arabia.png",
        "detailed_track_image": "Detailed_Saudi_Arabia.jpg",
        "detailed_track_attribution": "Joseph Azrak, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 2,
        "wiki": "2024_Saudi_Arabian_Grand_Prix",
        "date": "9th March",
    },
    "australia": {
        "circuit_id": "circuit_id_albert_park",
        "display_name": "Australia",
        "f1_website": "2024/australia",
        "flag": "Flag_of_Australia.png",
        "detailed_flag": "Australia.png",
        "annotated_layout": "australia.avif",
        "layout": "australia.png",
        "detailed_track_image": "Detailed_Australia.jpg",
        "detailed_track_attribution": "Chris Phutully, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "round": 3,
        "wiki": "2024_Australian_Grand_Prix",
        "date": "24th March",
    },
    "japan": {
        "circuit_id": "circuit_id_suzuka",
        "display_name": "Japan",
        "f1_website": "2024/japan",
        "flag": "Flag_of_Japan.png",
        "detailed_flag": "Japan.png",
        "annotated_layout": "japan.avif",
        "layout": "japan.png",
        "detailed_track_image": "Detailed_Japan.jpg",
        "detailed_track_attribution": "Tokumeigakarinoaoshima, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 4,
        "wiki": "2024_Japanese_Grand_Prix",
        "date": "7th April",
    },
    "china": {
        "circuit_id": "circuit_id_shanghai",
        "display_name": "China",
        "f1_website": "2024/china",
        "flag": "Flag_of_China.png",
        "detailed_flag": "China.png",
        "annotated_layout": "china.avif",
        "layout": "china.png",
        "detailed_track_image": "Detailed_China.jpg",
        "detailed_track_attribution": "sjiong, CC BY-SA 2.0 <https://creativecommons.org/licenses/by-sa/2.0>, via Wikimedia Commons",
        "round": 5,
        "wiki": "2024_Chinese_Grand_Prix",
        "date": "21st April",
    },
    "miami": {
        "circuit_id": "circuit_id_miami",
        "display_name": "Miami",
        "f1_website": "2024/miami",
        "flag": "Flag_of_USA.png",
        "detailed_flag": "USA.png",
        "annotated_layout": "miami.avif",
        "layout": "miami.png",
        "detailed_track_image": "Detailed_Miami.jpg",
        "detailed_track_attribution": "Bassfish22, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 6,
        "wiki": "2024_Miami_Grand_Prix",
        "date": "5th May",
    },
    "imola": {
        "circuit_id": "circuit_id_imola",
        "display_name": "Imola",
        "f1_website": "2024/emiliaromagna",
        "flag": "Flag_of_Italy.png",
        "detailed_flag": "Italy.png",
        "annotated_layout": "imola.avif",
        "layout": "imola.png",
        "detailed_track_image": "Detailed_Imola.jpg",
        "detailed_track_attribution": "",
        "round": 7,
        "wiki": "2024_Emilia_Romagna_Grand_Prix",
        "date": "19th May",
    },
    "monaco": {
        "circuit_id": "circuit_id_monaco",
        "display_name": "Monaco",
        "f1_website": "2024/monaco",
        "flag": "Flag_of_Monaco.png",
        "detailed_flag": "Monaco.png",
        "annotated_layout": "monaco.avif",
        "layout": "monaco.png",
        "detailed_track_image": "Detailed_Monaco.jpg",
        "detailed_track_attribution": "Alexander Migl, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 8,
        "wiki": "2024_Monaco_Grand_Prix",
        "date": "26th May",
    },
    "canada": {
        "circuit_id": "circuit_id_villeneuve",
        "display_name": "Canada",
        "f1_website": "2024/canada",
        "flag": "Flag_of_Canada.png",
        "detailed_flag": "Canada.png",
        "annotated_layout": "canada.avif",
        "layout": "canada.png",
        "detailed_track_image": "Detailed_Canada.jpg",
        "detailed_track_attribution": "kevint3141 from Kitchener, Canada, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "round": 9,
        "wiki": "2024_Canadian_Grand_Prix",
        "date": "9th June",
    },
    "spain": {
        "circuit_id": "circuit_id_catalunya",
        "display_name": "Spain",
        "f1_website": "2024/spain",
        "flag": "Flag_of_Spain.png",
        "detailed_flag": "Spain.png",
        "annotated_layout": "spain.avif",
        "layout": "spain.png",
        "detailed_track_image": "Detailed_Spain.jpg",
        "detailed_track_attribution": "Wilnel José Verdú Guerrero, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 10,
        "wiki": "2024_Spanish_Grand_Prix",
        "date": "23rd June",
    },
    "austria": {
        "circuit_id": "circuit_id_red_bull_ring",
        "display_name": "Austria",
        "f1_website": "2024/austria",
        "flag": "Flag_of_Austria.png",
        "detailed_flag": "Austria.png",
        "annotated_layout": "austria.avif",
        "layout": "austria.png",
        "detailed_track_image": "Detailed_Austria.jpg",
        "detailed_track_attribution": "https://www.flickr.com/photos/pedrik, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "round": 11,
        "wiki": "2024_Austrian_Grand_Prix",
        "date": "30th June",
    },
    "uk": {
        "circuit_id": "circuit_id_silverstone",
        "display_name": "United Kingdom",
        "f1_website": "2024/great-britain",
        "flag": "Flag_of_UK.png",
        "detailed_flag": "United_Kingdom.png",
        "annotated_layout": "uk.avif",
        "layout": "uk.png",
        "detailed_track_image": "Detailed_United_Kingdom.jpg",
        "detailed_track_attribution": "Becketts Stand, Silverstone. by David Ashcroft, CC BY-SA 2.0 <https://creativecommons.org/licenses/by-sa/2.0>, via Wikimedia Commons",
        "round": 12,
        "wiki": "2024_British_Grand_Prix",
        "date": "7th July",
    },
    "hungary": {
        "circuit_id": "circuit_id_hungaroring",
        "display_name": "Hungary",
        "f1_website": "2024/hungary",
        "flag": "Flag_of_Hungary.png",
        "detailed_flag": "Hungary.png",
        "annotated_layout": "hungary.avif",
        "layout": "hungary.png",
        "detailed_track_image": "Detailed_Hungary.jpg",
        "detailed_track_attribution": "Derzsi Elekes Andor (talk · contribs), CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 13,
        "wiki": "2024_Hungarian_Grand_Prix",
        "date": "21st July",
    },
    "belgium": {
        "circuit_id": "circuit_id_spa",
        "display_name": "Belgium",
        "f1_website": "2024/belgium",
        "flag": "Flag_of_Belgium.png",
        "detailed_flag": "Belgium.png",
        "annotated_layout": "belgium.avif",
        "layout": "belgium.png",
        "detailed_track_image": "Detailed_Belgium.jpg",
        "detailed_track_attribution": "Cutkiller2018, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 14,
        "wiki": "2024_Belgian_Grand_Prix",
        "date": "28th July",
    },
    "netherlands": {
        "circuit_id": "circuit_id_zandvoort",
        "display_name": "Netherlands",
        "f1_website": "2024/netherlands",
        "flag": "Flag_of_Netherlands.png",
        "detailed_flag": "Netherlands.png",
        "annotated_layout": "netherlands.avif",
        "layout": "netherlands.png",
        "detailed_track_image": "Detailed_Netherlands.jpg",
        "detailed_track_attribution": "dronepicr, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "round": 15,
        "wiki": "2024_Dutch_Grand_Prix",
        "date": "25th August",
    },
    "italy": {
        "circuit_id": "circuit_id_monza",
        "display_name": "Italy",
        "f1_website": "2024/italy",
        "flag": "Flag_of_Italy.png",
        "detailed_flag": "Italy.png",
        "annotated_layout": "italy.avif",
        "layout": "italy.png",
        "detailed_track_image": "Detailed_Italy.jpg",
        "detailed_track_attribution": "pedrik, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "round": 16,
        "wiki": "2024_Italian_Grand_Prix",
        "date": "1st September",
    },
    "azerbaijan": {
        "circuit_id": "circuit_id_baku",
        "display_name": "Azerbaijan",
        "f1_website": "2024/azerbaijan",
        "flag": "Flag_of_Azerbaijan.png",
        "detailed_flag": "Azerbaijan.png",
        "annotated_layout": "azerbaijan.avif",
        "layout": "azerbaijan.png",
        "detailed_track_image": "Detailed_Azerbaijan.jpg",
        "detailed_track_attribution": "President.az, CC BY 4.0 <https://creativecommons.org/licenses/by/4.0>, via Wikimedia Commons",
        "round": 17,
        "wiki": "2024_Azerbaijan_Grand_Prix",
        "date": "15th September",
    },
    "singapore": {
        "circuit_id": "circuit_id_marina_bay",
        "display_name": "Singapore",
        "f1_website": "2024/singapore",
        "flag": "Flag_of_Singapore.png",
        "detailed_flag": "Singapore.png",
        "annotated_layout": "singapore.avif",
        "layout": "singapore.png",
        "detailed_track_image": "Detailed_Singapore.jpg",
        "detailed_track_attribution": "chensiyuan, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 18,
        "wiki": "2024_Singapore_Grand_Prix",
        "date": "22nd September",
    },
    "usa": {
        "circuit_id": "circuit_id_americas",
        "display_name": "United States",
        "f1_website": "2024/united-states",
        "flag": "Flag_of_USA.png",
        "detailed_flag": "USA.png",
        "annotated_layout": "united-states.avif",
        "layout": "united_states.png",
        "detailed_track_image": "Detailed_United_States.jpg",
        "detailed_track_attribution": "Zach Catanzareti Photo, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "round": 19,
        "wiki": "2024_United_States_Grand_Prix",
        "date": "20th October",
    },
    "mexico": {
        "circuit_id": "circuit_id_rodriguez",
        "display_name": "Mexico",
        "f1_website": "2024/mexico",
        "flag": "Flag_of_Mexico.png",
        "detailed_flag": "Mexico.png",
        "annotated_layout": "mexico.avif",
        "layout": "mexico.png",
        "detailed_track_image": "Detailed_Mexico.jpg",
        "detailed_track_attribution": "Tsoncch22, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 20,
        "wiki": "2024_Mexican_Grand_Prix",
        "date": "27th October",
    },
    "brazil": {
        "circuit_id": "circuit_id_interlagos",
        "display_name": "Brazil",
        "f1_website": "2024/brazil",
        "flag": "Flag_of_Brazil.png",
        "detailed_flag": "Brazil.png",
        "annotated_layout": "brazil.avif",
        "layout": "brazil.png",
        "detailed_track_image": "Detailed_Brazil.jpg",
        "detailed_track_attribution": "Boaventuravinicius, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        "round": 21,
        "wiki": "2024_Brazilian_Grand_Prix",
        "date": "3rd November",
    },
    "las-vegas": {
        "circuit_id": "circuit_id_vegas",
        "display_name": "Las Vegas",
        "f1_website": "2024/las-vegas",
        "flag": "Flag_of_USA.png",
        "detailed_flag": "USA.png",
        "annotated_layout": "las-vegas.avif",
        "layout": "las_vegas.png",
        "detailed_track_image": "Detailed_Las_Vegas.jpg",
        "detailed_track_attribution": "5chw4r7z, CC BY-SA 2.0 <https://creativecommons.org/licenses/by-sa/2.0>, via Wikimedia Commons",
        "round": 22,
        "wiki": "2024_Las_Vegas_Grand_Prix",
        "date": "23rd November",
    },
    "qatar": {
        "circuit_id": "circuit_id_losail",
        "display_name": "Qatar",
        "f1_website": "2024/qatar",
        "flag": "Flag_of_Qatar.png",
        "detailed_flag": "Qatar.png",
        "annotated_layout": "qatar.avif",
        "layout": "qatar.png",
        "detailed_track_image": "Detailed_Qatar.jpg",
        "detailed_track_attribution": "Trinidade, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
        "round": 23,
        "wiki": "2024_Qatar_Grand_Prix",
        "date": "1st December",
    },
    "uae": {
        "circuit_id": "circuit_id_yas_marina",
        "display_name": "Abu Dhabi",
        "f1_website": "2024/united-arab-emirates",
        "flag": "Flag_of_UAE.png",
        "detailed_flag": "Abu_Dhabi.png",
        "annotated_layout": "uae.avif",
        "layout": "uae.png",
        "detailed_track_image": "Detailed_Abu_Dhabi.jpg",
        "detailed_track_attribution": "Cesar I. Martins, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
        "round": 24,
        "wiki": "2024_Abu_Dhabi_Grand_Prix",
        "date": "8th December",
    },
}