TRACK_METADATA = {
    "bahrain": {
        "display_name": "Bahrain",
        "f1_website": "2024/bahrain",
        "flag": "Flag_of_Bahrain.png",
        "layout": "bahrain.avif",
        "round": 1,
        "wiki": "2024_Bahrain_Grand_Prix",
    },
    "saudi-arabia": {
        "display_name": "Saudi Arabia",
        "f1_website": "2024/saudi-arabia",
        "flag": "Flag_of_Saudi_Arabia.png",
        "layout": "saudi-arabia.avif",
        "round": 2,
        "wiki": "2024_Saudi_Arabian_Grand_Prix",
    },
    "australia": {
        "display_name": "Australia",
        "f1_website": "2024/australia",
        "flag": "Flag_of_Australia.png",
        "layout": "australia.avif",
        "round": 3,
        "wiki": "2024_Australian_Grand_Prix",
    },
    "japan": {
        "display_name": "Japan",
        "f1_website": "2024/japan",
        "flag": "Flag_of_Japan.png",
        "layout": "japan.avif",
        "round": 4,
        "wiki": "2024_Japanese_Grand_Prix",
    },
    "china": {
        "display_name": "China",
        "f1_website": "2024/china",
        "flag": "Flag_of_China.png",
        "layout": "china.avif",
        "round": 5,
        "wiki": "2024_Chinese_Grand_Prix",
    },
    "miami": {
        "display_name": "Miami",
        "f1_website": "2024/miami",
        "flag": "Flag_of_USA.png",
        "layout": "miami.avif",
        "round": 6,
        "wiki": "2024_Miami_Grand_Prix",
    },
    "imola": {
        "display_name": "Imola",
        "f1_website": "2024/emiliaromagna",
        "flag": "Flag_of_Italy.png",
        "layout": "imola.avif",
        "round": 7,
        "wiki": "2024_Emilia_Romagna_Grand_Prix",
    },
    "monaco": {
        "display_name": "Monaco",
        "f1_website": "2024/monaco",
        "flag": "Flag_of_Monaco.png",
        "layout": "monaco.avif",
        "round": 8,
        "wiki": "2024_Monaco_Grand_Prix",
    },
    "canada": {
        "display_name": "Canada",
        "f1_website": "2024/canada",
        "flag": "Flag_of_Canada.png",
        "layout": "canada.avif",
        "round": 9,
        "wiki": "2024_Canadian_Grand_Prix",
    },
    "spain": {
        "display_name": "Spain",
        "f1_website": "2024/spain",
        "flag": "Flag_of_Spain.png",
        "layout": "spain.avif",
        "round": 10,
        "wiki": "2024_Spanish_Grand_Prix",
    },
    "austria": {
        "display_name": "Austria",
        "f1_website": "2024/austria",
        "flag": "Flag_of_Austria.png",
        "layout": "austria.avif",
        "round": 11,
        "wiki": "2024_Austrian_Grand_Prix",
    },
    "uk": {
        "display_name": "United Kingdom",
        "f1_website": "2024/great-britain",
        "flag": "Flag_of_UK.png",
        "layout": "uk.avif",
        "round": 12,
        "wiki": "2024_British_Grand_Prix",
    },
    "hungary": {
        "display_name": "Hungary",
        "f1_website": "2024/hungary",
        "flag": "Flag_of_Hungary.png",
        "layout": "hungary.avif",
        "round": 13,
        "wiki": "2024_Hungarian_Grand_Prix",
    },
    "belgium": {
        "display_name": "Belgium",
        "f1_website": "2024/belgium",
        "flag": "Flag_of_Belgium.png",
        "layout": "belgium.avif",
        "round": 14,
        "wiki": "2024_Belgian_Grand_Prix",
    },
    "netherlands": {
        "display_name": "Netherlands",
        "f1_website": "2024/netherlands",
        "flag": "Flag_of_Netherlands.png",
        "layout": "netherlands.avif",
        "round": 15,
        "wiki": "2024_Dutch_Grand_Prix",
    },
    "italy": {
        "display_name": "Italy",
        "f1_website": "2024/italy",
        "flag": "Flag_of_Italy.png",
        "layout": "italy.avif",
        "round": 16,
        "wiki": "2024_Italian_Grand_Prix",
    },
    "azerbaijan": {
        "display_name": "Azerbaijan",
        "f1_website": "2024/azerbaijan",
        "flag": "Flag_of_Azerbaijan.png",
        "layout": "azerbaijan.avif",
        "round": 17,
        "wiki": "2024_Azerbaijan_Grand_Prix",
    },
    "singapore": {
        "display_name": "Singapore",
        "f1_website": "2024/singapore",
        "flag": "Flag_of_Singapore.png",
        "layout": "singapore.avif",
        "round": 18,
        "wiki": "2024_Singapore_Grand_Prix",
    },
    "usa": {
        "display_name": "United States",
        "f1_website": "2024/united-states",
        "flag": "Flag_of_USA.png",
        "layout": "usa.avif",
        "round": 19,
        "wiki": "2024_United_States_Grand_Prix",
    },
    "mexico": {
        "display_name": "Mexico",
        "f1_website": "2024/mexico",
        "flag": "Flag_of_Mexico.png",
        "layout": "mexico.avif",
        "round": 20,
        "wiki": "2024_Mexican_Grand_Prix",
    },
    "brazil": {
        "display_name": "Brazil",
        "f1_website": "2024/brazil",
        "flag": "Flag_of_Brazil.png",
        "layout": "brazil.avif",
        "round": 21,
        "wiki": "2024_Brazilian_Grand_Prix",
    },
    "las-vegas": {
        "display_name": "Las Vegas",
        "f1_website": "2024/las-vegas",
        "flag": "Flag_of_USA.png",
        "layout": "las-vegas.avif",
        "round": 22,
        "wiki": "2024_Las_Vegas_Grand_Prix",
    },
    "qatar": {
        "display_name": "Qatar",
        "f1_website": "2024/qatar",
        "flag": "Flag_of_Qatar.png",
        "layout": "qatar.avif",
        "round": 23,
        "wiki": "2024_Qatar_Grand_Prix",
    },
    "uae": {
        "display_name": "Abu Dhabi",
        "f1_website": "2024/united-arab-emirates",
        "flag": "Flag_of_UAE.png",
        "layout": "uae.avif",
        "round": 24,
        "wiki": "2024_Abu_Dhabi_Grand_Prix",
    },
}