TRACK_METADATA = {
    "bahrain": {
        "display_name": "Bahrain",
        "flag": "Flag_of_Bahrain.png",
        "layout": "bahrain.avif",
        "round": 1,
    },
    "saudi-arabia": {
        "display_name": "Saudi Arabia",
        "flag": "Flag_of_Saudi_Arabia.png",
        "layout": "saudi-arabia.avif",
        "round": 2,
    },
    "australia": {
        "display_name": "Australia",
        "flag": "Flag_of_Australia.png",
        "layout": "australia.avif",
        "round": 3,
    },
    "japan": {
        "display_name": "Japan",
        "flag": "Flag_of_Japan.png",
        "layout": "japan.avif",
        "round": 4,
    },
    "china": {
        "display_name": "China",
        "flag": "Flag_of_China.png",
        "layout": "china.avif",
        "round": 5,
    },
    "miami": {
        "display_name": "Miami",
        "flag": "Flag_of_USA.png",
        "layout": "miami.avif",
        "round": 6,
    },
    "imola": {
        "display_name": "Imola",
        "flag": "Flag_of_Italy.png",
        "layout": "imola.avif",
        "round": 7,
    },
    "monaco": {
        "display_name": "Monaco",
        "flag": "Flag_of_Monaco.png",
        "layout": "monaco.avif",
        "round": 8,
    },
    "canada": {
        "display_name": "Canada",
        "flag": "Flag_of_Canada.png",
        "layout": "canada.avif",
        "round": 9,
    },
    "spain": {
        "display_name": "Spain",
        "flag": "Flag_of_Spain.png",
        "layout": "spain.avif",
        "round": 10,
    },
    "austria": {
        "display_name": "Austria",
        "flag": "Flag_of_Austria.png",
        "layout": "austria.avif",
        "round": 11,
    },
    "uk": {
        "display_name": "United Kingdom",
        "flag": "Flag_of_UK.png",
        "layout": "uk.avif",
        "round": 12,
    },
    "hungary": {
        "display_name": "Hungary",
        "flag": "Flag_of_Hungary.png",
        "layout": "hungary.avif",
        "round": 13,
    },
    "belgium": {
        "display_name": "Belgium",
        "flag": "Flag_of_Belgium.png",
        "layout": "belgium.avif",
        "round": 14,
    },
    "netherlands": {
        "display_name": "Netherlands",
        "flag": "Flag_of_Netherlands.png",
        "layout": "netherlands.avif",
        "round": 15,
    },
    "italy": {
        "display_name": "Italy",
        "flag": "Flag_of_Italy.png",
        "layout": "italy.avif",
        "round": 16,
    },
    "azerbaijan": {
        "display_name": "Azerbaijan",
        "flag": "Flag_of_Azerbaijan.png",
        "layout": "azerbaijan.avif",
        "round": 17,
    },
    "singapore": {
        "display_name": "Singapore",
        "flag": "Flag_of_Singapore.png",
        "layout": "singapore.avif",
        "round": 18,
    },
    "usa": {
        "display_name": "United States",
        "flag": "Flag_of_USA.png",
        "layout": "usa.avif",
        "round": 19,
    },
    "mexico": {
        "display_name": "Mexico",
        "flag": "Flag_of_Mexico.png",
        "layout": "mexico.avif",
        "round": 20,
    },
    "brazil": {
        "display_name": "Brazil",
        "flag": "Flag_of_Brazil.png",
        "layout": "brazil.avif",
        "round": 21,
    },
    "las-vegas": {
        "display_name": "Las Vegas",
        "flag": "Flag_of_USA.png",
        "layout": "las-vegas.avif",
        "round": 22,
    },
    "qatar": {
        "display_name": "Qatar",
        "flag": "Flag_of_Qatar.png",
        "layout": "qatar.avif",
        "round": 23,
    },
    "uae": {
        "display_name": "Abu Dhabi",
        "flag": "Flag_of_UAE.png",
        "layout": "uae.avif",
        "round": 24,
    },
}